// <auto-generated />
namespace cpl_azure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6));
        
        string IMigrationMetadata.Id
        {
            get { return "201309011156209_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
