/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module cpla.models {
    /** Generated from cpl_azure.Models.AboutMe **/
    export interface AboutMe {
        AboutMeId: number;
        Biographie: string;
    }
    /** Generated from cpl_azure.Models.News **/
    export interface News {
        NewsId: number;
        Title: string;
        Summary: string;
        Content: string;
    }
    /** Generated from cpl_azure.Models.Paints **/
    export interface Paints {
        PaintId: number;
        Name: string;
        Description: string;
        Year: string;
        Picture: string;
        Size: string;
        Order: number;
    }
}
